import {
  BarChart3,
  LayoutDashboard,
  ChevronRight,
  PanelsTopLeft,
  Settings,
  Target,
  Upload,
  ShieldCheck,
  Users,
  UserPlus,
} from 'lucide-react';

export const sidebarModules = [
  {
    key: 'dashboard',
    label: 'Dashboard',
    href: '/dashboard',
    icon: LayoutDashboard,
    roles: ['viewer'],
    enabled: true,
  },
  {
    key: 'customer-details',
    accessKey: 'customers',
    label: 'Customer Details',
    href: '/customers/details',
    icon: Users,
    roles: ['viewer'],
    enabled: true,
  },
  {
    key: 'customer-sales',
    accessKey: 'customers',
    label: 'Customer Sales',
    href: '/customers/sales',
    icon: Users,
    roles: ['viewer'],
    enabled: true,
  },
  {
    key: 'analytics',
    label: 'Analytics',
    href: '/analytics',
    icon: BarChart3,
    roles: ['viewer'],
    enabled: true,
  },
  {
    key: 'custom-dashboards',
    label: 'Reports',
    href: '/dashboards',
    icon: PanelsTopLeft,
    roles: ['viewer'],
    enabled: true,
  },
  {
    key: 'import',
    label: 'Import Data',
    href: '/import',
    icon: Upload,
    roles: ['manager'],
    enabled: true,
  },
  {
    key: 'customer-segment-import',
    accessKey: 'campaigns',
    label: 'Customer Segment Import',
    href: '/segments/import',
    icon: Upload,
    roles: ['manager'],
    enabled: true,
  },
  {
    key: 'campaign-master',
    accessKey: 'campaigns',
    label: 'Campaign Master',
    href: '/campaigns',
    icon: Target,
    roles: ['viewer'],
    children: [
      {
        key: 'campaigns-child',
        accessKey: 'campaigns',
        label: 'Campaigns',
        href: '/campaigns',
        icon: ChevronRight,
        roles: ['viewer'],
        enabled: true,
      },
      {
        key: 'segments-child',
        accessKey: 'campaigns',
        label: 'Segments',
        href: '/segments',
        icon: ChevronRight,
        roles: ['manager'],
        enabled: true,
      },
      {
        key: 'templates-child',
        accessKey: 'templates',
        label: 'Templates',
        href: '/templates',
        icon: ChevronRight,
        roles: ['viewer'],
        enabled: true,
      },
      {
        key: 'whatsapp-child',
        accessKey: 'whatsapp',
        label: 'WhatsApp',
        href: '/whatsapp',
        icon: ChevronRight,
        roles: ['analyst'],
        enabled: true,
      },
    ],
    enabled: true,
  },
  
  {
    key: 'roles',
    label: 'Roles',
    href: '/roles',
    icon: ShieldCheck,
    roles: ['admin'],
    enabled: true,
  },
  {
    key: 'users',
    label: 'Users',
    href: '/users',
    icon: UserPlus,
    roles: ['admin'],
    enabled: true,
  },
  {
    key: 'settings',
    label: 'Settings',
    href: '/settings',
    icon: Settings,
    roles: ['viewer'],
    enabled: true,
  },
];

export const getEnabledSidebarModules = () =>
  sidebarModules.filter((module) => module.enabled !== false);
